In [3]:
print("hola")
print("x3"*3)

hola
x3x3x3


In [4]:
print("o")
print(f"{"x"*5}Hola{"x"*5}")

o
xxxxxHolaxxxxx


In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: C:\Users\Anthony\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [ ]:
#lista=[1,2,3,4,5]
a1D=np.array([1,2,3,4])
a2D=np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a2D1=np.zeros((3,2))
a2D1.shape
a2D1.size

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
np.full((3,2),8)

array([[8, 8],
       [8, 8],
       [8, 8]])

In [20]:
print(np.linspace(0,6,10))

[0.         0.66666667 1.33333333 2.         2.66666667 3.33333333
 4.         4.66666667 5.33333333 6.        ]


In [21]:
np.random.rand(3,2)

array([[2.61653876e-04, 7.27147311e-01],
       [5.28528034e-01, 2.93049475e-01],
       [3.88626198e-01, 8.58743322e-01]])

CREAR MATRICES

In [23]:
#matriz unitarias
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])